name = "website"
compatibility_date = "2024-06-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "KV"
id = "bca8e10458aa48ecb59e2f244d1635d3"

[[d1_databases]]
binding = "D1"
database_name = "internal"
database_id = "5fb17e9f-aab6-4a2c-9760-ed426ddfdd6e"

[[r2_buckets]]
binding = "R2"
bucket_name = "documents"
